source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZDISO8601DateFormatter_Example', :exclusive => true do
  pod "ZDISO8601DateFormatter", :path => "../"
end

target 'ZDISO8601DateFormatter_Tests', :exclusive => true do
  pod "ZDISO8601DateFormatter", :path => "../"

  
end
